//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuemolaWPF.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialiSfrido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaterialiSfrido()
        {
            this.MaterialiNomi = new HashSet<MaterialiNomi>();
        }
    
        public int Id { get; set; }
        public string NomeSfrido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialiNomi> MaterialiNomi { get; set; }
    }
}
