//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuemolaWPF.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MecsidEntities : DbContext
    {
        public MecsidEntities()
            : base("name=MecsidEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Destinazione> Destinazione { get; set; }
        public virtual DbSet<MaterialiNomi> MaterialiNomi { get; set; }
        public virtual DbSet<MaterialiSfrido> MaterialiSfrido { get; set; }
        public virtual DbSet<MolaGrana> MolaGrana { get; set; }
        public virtual DbSet<MolaMarca> MolaMarca { get; set; }
        public virtual DbSet<MolaTipo> MolaTipo { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<TemplateRicette> TemplateRicette { get; set; }
    }
}
